### PR TITLE
feat(coil-extenstion): add initiateTip call

### PR DESCRIPTION
**Pull request by njlie**
Updates the tipping call to use `initiateTip` and its associated input parameters.

Blocked by: https://github.com/coilhq/coil/pull/4714.

### CODE REVIEW

**Comment by njlie** [comment]
@sublimator Any ideas why the upkeep job is failing? I can't discern an error from the logs.

**Comment by sublimator** [comment]
@njlie 

Seems like the CI is failing due to code not being formatted with prettier.
Is husky not working for you? (I recently upgraded to v6) 
executing `yarn rebuild` may help

**Comment by sublimator** [comment]
image

@njlie 
To be more specific ^^

**Review by mwill8886 — APPROVED** [review]

**Review by sublimator — APPROVED** [review]

**Comment by matdehaast** [comment]
Ouch, this may have been premature.

The reason being is that initateTip will be required to specify a paymentMethod. Which the current tipping doesn't allow

**Pull request merged**
