### PR TITLE
refactor(web-monetization-demo): refactor and update README.md

### PR DESCRIPTION
**Pull request by sublimator**

### CODE REVIEW

**Comment by sublimator** [comment]
Interesting! It's nice to have something self-contained (no redis etc).
Pondering removing or just linking to it in the readme ?

**Comment by wilsonianb** [comment]
I was feeling compelled to remove the verifier here instead of having more or less the same implementation (to maintain) in two places.
(And the receipt-verifier shouldn't be moved to this monorepo, since can be used for ILP more generally than just web monetization.)

**Comment by sublimator** [comment]
I think a toy example has some value (and I don't mind maintaining it), so I just added a link to the production verifier in the readme. Could actually do both, given the addition is just a dependency and altered script.

**Comment by sublimator** [comment]
Ah, the balances and SPSP proxy apis are on different ports

**Pull request merged**
