### PR TITLE
feat: update tip settings on initial tip view

### PR DESCRIPTION
**Pull request by mwill8886**
resolves: COIL-1810

added command to update the tipping settings data when the tip view is loaded.

### CODE REVIEW

**Review by traviscrist — APPROVED** [review]

**Review by njlie — APPROVED** [review]

**Review by RLuckom — APPROVED** [review]

**Review by davebarr — APPROVED** [review]

**Comment by sublimator** [comment]
image

Seems to be flickering when you hover over the icons in the footer.
Checking on `main` to see if it's there too, or if it's a regression somehow

**Comment by sublimator** [comment]
It seems to be a regression, probably due to react rendering quirks

**Review by sublimator — CHANGES_REQUESTED** [review]
See here:
https://github.com/coilhq/web-monetization-projects/pull/2592#issuecomment-1038738135

**Comment by sublimator** [comment]
So, weird, went back to the branch to double check and it seems fine

**Pull request merged**
